/**
 * Generated by `createservice acquiring.CreateAcquiringPaymentDetailsService --type mutations`
 */

const conf = require('@open-condo/config')
const { checkDvAndSender } = require('@open-condo/keystone/plugins/dvAndSender')
const { GQLCustomSchema, getById, find } = require('@open-condo/keystone/schema')
const access = require('@condo/domains/acquiring/access/CreateAcquiringPaymentDetailsService')
const { GQLError, GQLErrorCode: { BAD_USER_INPUT, INTERNAL_ERROR } } = require('@open-condo/keystone/errors')
const { getProviderByIntegrationName } = require('@condo/domains/acquiring/integrations/providers')
const { DV_VERSION_MISMATCH, WRONG_FORMAT, NOT_FOUND } = require('@condo/domains/common/constants/errors')

/**
 * List of possible errors, that this custom schema can throw
 * They will be rendered in documentation section in GraphiQL for this custom schema
 */
const ERRORS = {
    DV_VERSION_MISMATCH: {
        mutation: 'createAcquiringPaymentDetails',
        variable: ['data', 'dv'],
        code: BAD_USER_INPUT,
        type: DV_VERSION_MISMATCH,
        message: 'Wrong value for data version number',
    },
    WRONG_SENDER_FORMAT: {
        mutation: 'createAcquiringPaymentDetails',
        variable: ['data', 'sender'],
        code: BAD_USER_INPUT,
        type: WRONG_FORMAT,
        message: 'Invalid format of "sender" field value. {details}',
        correctExample: '{ "dv": 1, "fingerprint": "uniq-device-or-container-id" }',
        messageInterpolation: { details: 'Please, check the example for details' },
    },
    MULTI_PAYMENT_NOT_FOUND: {
        mutation: 'createAcquiringPaymentDetails',
        variable: ['data', 'multiPayment', 'id'],
        code: BAD_USER_INPUT,
        type: NOT_FOUND,
        message: 'MultiPayment with specified id was not found, or has no linked payment',
    },
    PROVIDER_NOT_CONFIGURED: {
        mutation: 'createAcquiringPaymentDetails',
        code: BAD_USER_INPUT,
        type: NOT_FOUND,
        message: 'No supported payment provider is configured for this organization',
        messageForUser: 'api.acquiring.createAcquiringPaymentDetails.PROVIDER_NOT_CONFIGURED',
    },
    PROVIDER_CALL_FAILED: {
        mutation: 'createAcquiringPaymentDetails',
        code: INTERNAL_ERROR,
        type: 'PROVIDER_CALL_FAILED',
        message: 'Payment provider call failed: {error}',
        messageForUser: 'api.acquiring.createAcquiringPaymentDetails.PROVIDER_CALL_FAILED',
        messageInterpolation: { error: 'reason of the failure' },
    },
}

const CreateAcquiringPaymentDetailsService = new GQLCustomSchema('CreateAcquiringPaymentDetailsService', {
    types: [
        {
            access: true,
            type: 'input CreateAcquiringPaymentDetailsInput { dv: Int!, sender: SenderFieldInput!, multiPayment: MultiPaymentWhereUniqueInput! }',
        },
        {
            access: true,
            type: 'type CreateAcquiringPaymentDetailsOutput { providerSlug: String!, qrText: String, qrImageBase64: String }',
        },
    ],

    mutations: [
        {
            access: access.canCreateAcquiringPaymentDetails,
            schema: 'createAcquiringPaymentDetails(data: CreateAcquiringPaymentDetailsInput!): CreateAcquiringPaymentDetailsOutput',
            doc: {
                summary: 'Asks the acquiring provider configured for the multi-payment\'s organization to start a payment, ' +
                    'and returns whatever is needed to render a checkout on the client (a QR code, for now).',
                errors: ERRORS,
            },
            resolver: async (parent, args, context) => {
                const { data } = args
                checkDvAndSender(data, ERRORS.DV_VERSION_MISMATCH, ERRORS.WRONG_SENDER_FORMAT, context)

                const multiPaymentId = data.multiPayment.id
                const multiPayment = await getById('MultiPayment', multiPaymentId)
                if (!multiPayment) throw new GQLError(ERRORS.MULTI_PAYMENT_NOT_FOUND, context)

                const payments = await find('Payment', { multiPayment: { id: multiPaymentId }, deletedAt: null })
                const payment = payments[0]
                if (!payment) throw new GQLError(ERRORS.MULTI_PAYMENT_NOT_FOUND, context)

                const acquiringContext = await getById('AcquiringIntegrationContext', payment.context)
                if (!acquiringContext) throw new GQLError(ERRORS.PROVIDER_NOT_CONFIGURED, context)

                const integration = await getById('AcquiringIntegration', acquiringContext.integration)
                const provider = integration && getProviderByIntegrationName(integration.name)
                if (!provider) throw new GQLError(ERRORS.PROVIDER_NOT_CONFIGURED, context)

                let paymentDetails
                try {
                    paymentDetails = await provider.createPayment(acquiringContext.settings, {
                        amount: multiPayment.amount,
                        description: `Payment #${multiPaymentId}`,
                        orderId: multiPaymentId,
                        callbackUrl: `${conf.SERVER_URL}/api/webhooks/acquiring/${provider.slug}`,
                    })
                } catch (error) {
                    throw new GQLError({
                        ...ERRORS.PROVIDER_CALL_FAILED,
                        messageInterpolation: { error: error.message },
                    }, context)
                }

                return {
                    providerSlug: provider.slug,
                    qrText: paymentDetails.qrText || null,
                    qrImageBase64: paymentDetails.qrImageBase64 || null,
                }
            },
        },
    ],

})

module.exports = {
    CreateAcquiringPaymentDetailsService,
}
