/**
 * Generated by `createservice acquiring.CreateAcquiringPaymentDetailsService --type mutations`
 */
const get = require('lodash/get')

const { throwAuthenticationError } = require('@open-condo/keystone/apolloErrorFormatter')
const { getById } = require('@open-condo/keystone/schema')

const { RESIDENT } = require('@condo/domains/user/constants/common')

async function canCreateAcquiringPaymentDetails ({ authentication: { item: user }, args }) {
    if (!user) return throwAuthenticationError()
    if (user.deletedAt) return false
    if (user.isAdmin) return true

    if (user.type === RESIDENT) {
        const multiPaymentId = get(args, ['data', 'multiPayment', 'id'])
        if (!multiPaymentId) return false

        const multiPayment = await getById('MultiPayment', multiPaymentId)
        return Boolean(multiPayment) && multiPayment.user === user.id
    }

    return false
}

/*
  Rules are logical functions that used for list access, and may return a boolean (meaning
  all or no items are available) or a set of filters that limit the available items.
*/
module.exports = {
    canCreateAcquiringPaymentDetails,
}
